# Generated by Django 4.1.5 on 2023-01-16 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_alter_category_subscribers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisment',
            name='category',
            field=models.CharField(choices=[(3, 'ДД'), (9, 'Зельевары'), (7, 'Кузнецы'), (4, 'Торговцы'), (5, 'Гилдмастеры'), (6, 'Квестгиверы'), (1, 'Танки'), (8, 'Кожевники'), (10, 'Мастера заклинаний'), (2, 'Хилы')], max_length=255),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
