# Generated by Django 4.1.5 on 2023-01-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_alter_advertisment_category_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisment',
            name='category',
            field=models.CharField(choices=[(2, 'Хилы'), (3, 'ДД'), (7, 'Кузнецы'), (5, 'Гилдмастеры'), (1, 'Танки'), (8, 'Кожевники'), (10, 'Мастера заклинаний'), (4, 'Торговцы'), (9, 'Зельевары'), (6, 'Квестгиверы')], max_length=255),
        ),
    ]
