# Generated by Django 4.1.5 on 2023-01-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_alter_advertisment_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='advertisment',
            name='category',
            field=models.CharField(choices=[(3, 'ДД'), (4, 'Торговцы'), (8, 'Кожевники'), (9, 'Зельевары'), (10, 'Мастера заклинаний'), (6, 'Квестгиверы'), (5, 'Гилдмастеры'), (7, 'Кузнецы'), (1, 'Танки'), (2, 'Хилы')], max_length=255),
        ),
    ]
