# Generated by Django 4.1.5 on 2023-01-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_category_alter_advertisment_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisment',
            name='category',
            field=models.CharField(choices=[(4, 'Торговцы'), (9, 'Зельевары'), (8, 'Кожевники'), (7, 'Кузнецы'), (1, 'Танки'), (10, 'Мастера заклинаний'), (6, 'Квестгиверы'), (3, 'ДД'), (2, 'Хилы'), (5, 'Гилдмастеры')], max_length=255),
        ),
    ]
