# Generated by Django 4.1.5 on 2023-01-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_alter_advertisment_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisment',
            name='category',
            field=models.CharField(choices=[(9, 'Зельевары'), (1, 'Танки'), (8, 'Кожевники'), (5, 'Гилдмастеры'), (3, 'ДД'), (2, 'Хилы'), (4, 'Торговцы'), (6, 'Квестгиверы'), (10, 'Мастера заклинаний'), (7, 'Кузнецы')], max_length=255),
        ),
    ]
