# Generated by Django 4.1.5 on 2023-01-16 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_alter_advertisment_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AlterField(
            model_name='advertisment',
            name='category',
            field=models.CharField(choices=[(2, 'Хилы'), (6, 'Квестгиверы'), (5, 'Гилдмастеры'), (10, 'Мастера заклинаний'), (4, 'Торговцы'), (1, 'Танки'), (7, 'Кузнецы'), (8, 'Кожевники'), (3, 'ДД'), (9, 'Зельевары')], max_length=255),
        ),
    ]
