# Generated by Django 4.1.5 on 2023-01-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0013_remove_advertisment_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisment',
            name='category',
            field=models.CharField(blank=True, choices=[(5, 'Гилдмастеры'), (1, 'Танки'), (10, 'Мастера заклинаний'), (4, 'Торговцы'), (9, 'Зельевары'), (8, 'Кожевники'), (2, 'Хилы'), (3, 'ДД'), (7, 'Кузнецы'), (6, 'Квестгиверы')], max_length=255),
        ),
    ]
