# Generated by Django 4.1.5 on 2023-01-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0014_advertisment_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisment',
            name='category',
            field=models.CharField(blank=True, choices=[(6, 'Квестгиверы'), (5, 'Гилдмастеры'), (7, 'Кузнецы'), (1, 'Танки'), (2, 'Хилы'), (8, 'Кожевники'), (10, 'Мастера заклинаний'), (4, 'Торговцы'), (3, 'ДД'), (9, 'Зельевары')], max_length=255),
        ),
    ]
