# Generated by Django 4.1.5 on 2023-01-16 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0015_alter_advertisment_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisment',
            name='category',
        ),
    ]
