# Generated by Django 4.1.5 on 2023-01-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0017_advertisment_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisment',
            name='category',
            field=models.CharField(choices=[(8, 'Кожевники'), (4, 'Торговцы'), (10, 'Мастера заклинаний'), (2, 'Хилы'), (9, 'Зельевары'), (3, 'ДД'), (7, 'Кузнецы'), (5, 'Гилдмастеры'), (1, 'Танки'), (6, 'Квестгиверы')], default=1, max_length=255),
        ),
    ]
