# Generated by Django 4.1.5 on 2023-01-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0018_alter_advertisment_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisment',
            name='category',
            field=models.CharField(choices=[(10, 'Мастера заклинаний'), (5, 'Гилдмастеры'), (1, 'Танки'), (2, 'Хилы'), (9, 'Зельевары'), (7, 'Кузнецы'), (4, 'Торговцы'), (3, 'ДД'), (6, 'Квестгиверы'), (8, 'Кожевники')], default=1, max_length=255),
        ),
    ]
