# Generated by Django 4.1.5 on 2023-01-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0019_alter_advertisment_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisment',
            name='count',
        ),
        migrations.RemoveField(
            model_name='advertisment',
            name='rating',
        ),
        migrations.AlterField(
            model_name='advertisment',
            name='category',
            field=models.CharField(choices=[(7, 'Кузнецы'), (6, 'Квестгиверы'), (4, 'Торговцы'), (3, 'ДД'), (2, 'Хилы'), (1, 'Танки'), (8, 'Кожевники'), (10, 'Мастера заклинаний'), (5, 'Гилдмастеры'), (9, 'Зельевары')], default=1, max_length=255),
        ),
    ]
