# Generated by Django 4.1.5 on 2023-01-18 19:08

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0020_remove_advertisment_count_remove_advertisment_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisment',
            name='category',
            field=models.CharField(choices=[('Кожевники', 'Кожевники'), ('Зельевары', 'Зельевары'), ('ДД', 'ДД'), ('Мастера заклинаний', 'Мастера заклинаний'), ('Квестгиверы', 'Квестгиверы'), ('Хилы', 'Хилы'), ('Гилдмастеры', 'Гилдмастеры'), ('Танки', 'Танки'), ('Кузнецы', 'Кузнецы'), ('Торговцы', 'Торговцы')], default='Танки', max_length=255),
        ),
        migrations.AlterField(
            model_name='advertisment',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='advertisment',
            name='head',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='responses',
            name='acceptresponse',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='responses',
            name='text',
            field=models.TextField(),
        ),
    ]
