# Generated by Django 4.1.5 on 2023-01-19 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0022_alter_advertisment_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responses',
            name='time_update',
        ),
        migrations.AlterField(
            model_name='advertisment',
            name='category',
            field=models.CharField(choices=[('Торговцы', 'Торговцы'), ('Кузнецы', 'Кузнецы'), ('Мастера заклинаний', 'Мастера заклинаний'), ('Хилы', 'Хилы'), ('Кожевники', 'Кожевники'), ('Гилдмастеры', 'Гилдмастеры'), ('Зельевары', 'Зельевары'), ('ДД', 'ДД'), ('Танки', 'Танки'), ('Квестгиверы', 'Квестгиверы')], default='Танки', max_length=255),
        ),
    ]
