# Generated by Django 4.1.5 on 2023-01-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0023_remove_responses_time_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='responses',
            name='time_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='advertisment',
            name='category',
            field=models.CharField(choices=[('Кожевники', 'Кожевники'), ('Зельевары', 'Зельевары'), ('Кузнецы', 'Кузнецы'), ('Мастера заклинаний', 'Мастера заклинаний'), ('Хилы', 'Хилы'), ('Танки', 'Танки'), ('Гилдмастеры', 'Гилдмастеры'), ('Торговцы', 'Торговцы'), ('ДД', 'ДД'), ('Квестгиверы', 'Квестгиверы')], default='Танки', max_length=255),
        ),
    ]
