# Generated by Django 4.1.5 on 2023-01-20 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0024_responses_time_update_alter_advertisment_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisment',
            name='category',
            field=models.CharField(choices=[('Мастера заклинаний', 'Мастера заклинаний'), ('Зельевары', 'Зельевары'), ('ДД', 'ДД'), ('Кожевники', 'Кожевники'), ('Квестгиверы', 'Квестгиверы'), ('Гилдмастеры', 'Гилдмастеры'), ('Торговцы', 'Торговцы'), ('Танки', 'Танки'), ('Кузнецы', 'Кузнецы'), ('Хилы', 'Хилы')], default='Танки', max_length=255),
        ),
    ]
